In [1]:
import numpy as np

## the basics

In [8]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b= np.array([[6.0,7.0, 8.0],[2.0, 5.0,9.0]])
print(b)

[[6. 7. 8.]
 [2. 5. 9.]]


In [19]:
# get dimension
b.ndim

2

In [6]:
# get shape
b.shape

(2, 3)

In [9]:
a.dtype

dtype('int16')

In [14]:
# get size
b.itemsize

8

In [13]:
# get total size
a.nbytes


6

## accessing/changing specific elements, rows, columns

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# get a specific element
a[1,5]

13

In [17]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# get column
a[:, 2]

array([ 3, 10])

In [23]:
# more fancy [startindex:endindex:stepsize]  
a[0,0:6:2]

array([1, 3, 5])

In [30]:
a[1,5]=20
print(a)

print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [31]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# 3d example

In [32]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
# get specific element
b[0,1,1]

4

In [34]:
# replace
b[:,1,:]=[[8,9],[8,8]]

In [35]:
print(b)

[[[1 2]
  [8 9]]

 [[5 6]
  [8 8]]]


## initializing different types of arrays

In [36]:
# all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((4,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
# any other no
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [40]:
# any other no(full like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
#random decimal nos
np.random.rand(4,2)

array([[0.56247693, 0.77548323],
       [0.49745286, 0.23234716],
       [0.89547001, 0.88433452],
       [0.29727526, 0.66152474]])

In [43]:
# random integer
np.random.randint(7,size=(3,3))

array([[3, 3, 3],
       [0, 6, 1],
       [3, 6, 2]])

In [44]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
#repeat an array
arr=np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [50]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## be careful while copying array

In [52]:
a= np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## mathematics

In [53]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a+2

array([3, 4, 5, 6])

In [55]:
a-2

array([-1,  0,  1,  2])

In [56]:
a*2

array([2, 4, 6, 8])

In [57]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [58]:
b= np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [59]:
a **2

array([ 1,  4,  9, 16])

In [60]:
# take sin 
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [61]:
# for more (https://docs.spicy.org/doc/numpy/reference/routines.math.html)

## linear algebra

In [65]:
a= np.full((2,3),1)
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [66]:
c= np.identity(3)
np.linalg.det(c)

1.0

In [67]:
## reference docs(https://numpy.org/doc/stable/reference/routines.linalg.html)

## statistics

In [68]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.min(stats)

1

In [70]:
np.max(stats)

6

In [71]:
np.min(stats, axis=0)

array([1, 2, 3])

In [73]:
np.min(stats ,axis=1) ##min of first and second row

array([1, 4])

In [74]:
np.sum(stats)

21

In [75]:
np.sum(stats, axis= 0)

array([5, 7, 9])

## reorganizing arrays

In [78]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print (after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [79]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [80]:
# horizontal stacking
h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## miscellaneous

# load data from file

In [89]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### boolean masking and aadvance indexing

In [90]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [91]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [92]:
## you can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,6]]

array([2, 4, 7])

In [93]:
np.any(filedata > 50, axis=0)


array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [94]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [96]:
(~(filedata>50 )&(filedata<100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])